import PDFDocument from "pdfkit";
import { computeLimitationWindow } from "../domain/filing-details";
import { formatIsoDateAsDisplay } from "../lib/format-ist-date";
import type { FilingPartyRecord } from "../repositories/filing-party-repository";
import type { FilingRecord } from "../repositories/filing-repository";

/**
 * Renders the draft-complaint PDF attached alongside "✅ Your complaint is
 * ready" (filing-review-workflow.ts's handleFilingDeclareInput). Mirrors the
 * shape of the dristiwa.netlify.app prototype's own DRAFT_DOC (title block,
 * numbered paragraphs, prayer, signature block, list of documents/witnesses)
 * — using this filing's own persisted fields, never re-derived from
 * anything but the same FilingRecord/FilingPartyRecord data
 * renderFilingReviewSummary (filing-details-sender.ts) already renders as
 * chat text.
 *
 * Deliberately a demo-quality template, not an attempt at legally rigorous
 * drafting (confirmed scope decision) — always in English, even in a
 * Malayalam journey, matching the prototype's own explicit choice ("drafts
 * stay in English ... as they do in practice"). Every page carries a
 * visible "demonstration only" line so this is never mistaken for a real
 * pleading.
 */

const PAGE_MARGIN = 56;
const DEMO_BANNER = "DEMONSTRATION ONLY — generated by a pilot service, not filed with any court, not legal advice.";

function fullNameOrBlank(party: FilingPartyRecord): string {
  return party.fullName ?? "";
}

function surname(party: FilingPartyRecord): string {
  const name = fullNameOrBlank(party).trim();
  const words = name.split(/\s+/).filter(Boolean);
  return words.length > 0 ? words[words.length - 1] : "Party";
}

/** `Complaint_S138_{complainant surname}_vs_{accused surname}.pdf` — mirrors the prototype's own filename convention. */
export function complaintPdfFilename(complainant: FilingPartyRecord, accused: FilingPartyRecord): string {
  return `Complaint_S138_${surname(complainant)}_vs_${surname(accused)}.pdf`;
}

const RETURN_REASON_TEXT: Record<string, string> = {
  funds: "insufficiency of funds",
  stop: "payment stopped by the drawer",
  acct: "the account being closed",
  sign: "the signature not matching bank records",
};

function partyDescriptor(party: FilingPartyRecord, role: "Complainant" | "Accused"): string {
  const address = party.address ?? "";
  return `${fullNameOrBlank(party)}, residing at ${address} (the ${role}).`;
}

function paragraph(doc: PDFKit.PDFDocument, index: number, text: string): void {
  doc.font("Helvetica-Bold").fontSize(10).text(`${index}. `, { continued: true }).font("Helvetica").text(text);
  doc.moveDown(0.6);
}

/**
 * Builds the PDF and resolves with the finished buffer. pdfkit streams its
 * output, so this is necessarily async — never a synchronous Buffer return.
 */
export function renderComplaintPdf(filing: FilingRecord, complainant: FilingPartyRecord, accused: FilingPartyRecord): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const court = filing.selectedCourt ?? "the court with jurisdiction";
    const amount = filing.chequeAmount ?? "";
    const returnReasonText = filing.returnReason ? RETURN_REASON_TEXT[filing.returnReason] ?? filing.returnReason : "the reason stated on the return memo";

    // ---- Title block -------------------------------------------------
    doc.font("Helvetica-Bold").fontSize(9).text(DEMO_BANNER, { align: "center" });
    doc.moveDown(1);
    doc.fontSize(13).text(`IN THE ${court.toUpperCase()}`, { align: "center" });
    doc.font("Helvetica").fontSize(9).text("(Court of the Judicial First Class Magistrate)", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).text("C.C. No. _______ of " + new Date().getFullYear(), { align: "center" });
    doc.fontSize(8).text("(Complaint under Section 200 of the Code of Criminal Procedure, 1973, read with Section 138 of the Negotiable Instruments Act, 1881)", {
      align: "center",
    });
    doc.moveDown(1);

    doc.fontSize(10).font("Helvetica").text(partyDescriptor(complainant, "Complainant"));
    doc.font("Helvetica-Bold").text("… Complainant", { align: "center" });
    doc.font("Helvetica").text("Versus", { align: "center" });
    doc.text(partyDescriptor(accused, "Accused"));
    doc.font("Helvetica-Bold").text("… Accused", { align: "center" });
    doc.moveDown(0.5);
    doc.text("COMPLAINT", { align: "center", underline: true });
    doc.moveDown(1);

    // ---- Numbered paragraphs ------------------------------------------
    let n = 1;
    paragraph(doc, n++, `The complainant is filing this complaint within the local limits of the jurisdiction of this Hon'ble Court.`);
    paragraph(
      doc,
      n++,
      `The accused, towards discharge of a legally enforceable debt due to the complainant, issued cheque bearing No. ${filing.chequeNumber ?? "____"} dated ${
        filing.chequeDate ? formatIsoDateAsDisplay(filing.chequeDate) : "____"
      } for Rs. ${amount} drawn on ${filing.bankBranch ?? "the drawee bank"}, in favour of the complainant.`,
    );
    paragraph(
      doc,
      n++,
      `The said cheque was presented for collection within the period of its validity and was returned unpaid on ${
        filing.memoDate ? formatIsoDateAsDisplay(filing.memoDate) : "____"
      } on account of ${returnReasonText}, vide the return memo of the said bank.`,
    );
    paragraph(
      doc,
      n++,
      `The complainant thereupon issued a statutory demand notice dated ${
        filing.noticeDate ? formatIsoDateAsDisplay(filing.noticeDate) : "____"
      }, calling upon the accused to pay the said sum within fifteen days of receipt.`,
    );
    paragraph(
      doc,
      n++,
      `The said notice was duly served on the accused on ${
        filing.serviceDate ? formatIsoDateAsDisplay(filing.serviceDate) : "____"
      }, as evidenced by the postal acknowledgement produced along with this complaint.`,
    );
    paragraph(
      doc,
      n++,
      filing.partPayment
        ? "The accused has made only a part payment since the notice, and a balance amount remains due and payable."
        : "The accused has failed and neglected to pay the said amount, or any part of it, within fifteen days of receipt of the said notice, and has thereby committed an offence punishable under Section 138 of the Negotiable Instruments Act, 1881.",
    );
    if (filing.serviceDate) {
      const window = computeLimitationWindow(filing.serviceDate);
      paragraph(
        doc,
        n++,
        `The cause of action for this complaint arose on ${formatIsoDateAsDisplay(
          window.causeOfActionDateIso,
        )}, on the expiry of fifteen days from the date of service of the notice, and this complaint is filed within the period of limitation prescribed by Section 142(1)(b) of the said Act (by ${formatIsoDateAsDisplay(
          window.limitationDeadlineIso,
        )}).`,
      );
    }
    if (filing.narrative && filing.narrative.trim().length > 0) {
      paragraph(doc, n++, filing.narrative.trim());
    }
    paragraph(
      doc,
      n++,
      filing.witnessPresent
        ? "The above facts are within the knowledge of a witness who was present and can be cited if required."
        : "No other person was present at the time the transaction giving rise to this debt took place.",
    );

    doc.moveDown(0.5);
    doc.font("Helvetica-Bold").fontSize(10).text("PRAYER", { align: "center", underline: true });
    doc.font("Helvetica").text(
      "It is therefore most respectfully prayed that this Hon'ble Court may be pleased to take cognizance of the offence, issue process to the accused, try and punish him for the offence punishable under Section 138 of the Negotiable Instruments Act, 1881, and award compensation to the complainant under Section 357 of the Code of Criminal Procedure, 1973, and grant such other reliefs as this Hon'ble Court may deem fit.",
    );
    doc.moveDown(1.5);
    doc.text(`Dated: ${formatIsoDateAsDisplay(new Date().toISOString().slice(0, 10))}`);
    doc.moveDown(0.5);
    doc.text("Complainant", { align: "right" });
    doc.text("Advocate for the complainant", { align: "right" });

    // ---- List of documents / witnesses ---------------------------------
    doc.addPage();
    doc.font("Helvetica-Bold").fontSize(9).text(DEMO_BANNER, { align: "center" });
    doc.moveDown(1);
    doc.fontSize(12).text("LIST OF DOCUMENTS", { align: "center", underline: true });
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(10);
    const documents = [
      `Cheque bearing No. ${filing.chequeNumber ?? "____"} dated ${filing.chequeDate ? formatIsoDateAsDisplay(filing.chequeDate) : "____"} for Rs. ${amount}.`,
      `Cheque return memo dated ${filing.memoDate ? formatIsoDateAsDisplay(filing.memoDate) : "____"}.`,
      `Office copy of the statutory demand notice dated ${filing.noticeDate ? formatIsoDateAsDisplay(filing.noticeDate) : "____"}.`,
      `Proof of service of the said notice, dated ${filing.serviceDate ? formatIsoDateAsDisplay(filing.serviceDate) : "____"}.`,
      "Complainant's ID proof.",
    ];
    documents.forEach((line, i) => paragraph(doc, i + 1, line));

    doc.moveDown(0.5);
    doc.font("Helvetica-Bold").fontSize(12).text("LIST OF WITNESSES", { align: "center", underline: true });
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(10);
    paragraph(doc, 1, `The complainant, ${fullNameOrBlank(complainant)}.`);
    if (filing.witnessPresent) {
      paragraph(doc, 2, "A witness present at the time of the transaction (named separately with the complainant).");
    }

    doc.end();
  });
}
